
package drrs.client;

import drrs.client.net.java.dev.jaxb.array.ObjectFactory;
import drrs.client.net.java.dev.jaxb.array.StringArray;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICampus", targetNamespace = "http://campusservice.server.drrs/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICampus {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://campusservice.server.drrs/ICampus/changeReservationRequest", output = "http://campusservice.server.drrs/ICampus/changeReservationResponse")
    public String changeReservation(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://campusservice.server.drrs/ICampus/getAvailableTimeSlotRequest", output = "http://campusservice.server.drrs/ICampus/getAvailableTimeSlotResponse")
    public String getAvailableTimeSlot(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://campusservice.server.drrs/ICampus/deleteRoomRequest", output = "http://campusservice.server.drrs/ICampus/deleteRoomResponse")
    public String deleteRoom(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        StringArray arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://campusservice.server.drrs/ICampus/createRoomRequest", output = "http://campusservice.server.drrs/ICampus/createRoomResponse")
    public String createRoom(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        StringArray arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://campusservice.server.drrs/ICampus/bookRoomRequest", output = "http://campusservice.server.drrs/ICampus/bookRoomResponse")
    public String bookRoom(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://campusservice.server.drrs/ICampus/cancelBookingRequest", output = "http://campusservice.server.drrs/ICampus/cancelBookingResponse")
    public String cancelBooking(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
